---
heat_template_version: 2016-04-08

parameters:
    job_name:
        type: string
        description: Name of job running this template
    ssh_key:
        type: string
        default: releng
        description: SSH Key name to use (Public key must exist in OpenStack)
    vm_0_count:
        type: number
        description: Number of VMs for 1st VM type
    vm_0_flavor:
        type: string
        default: v1-standard-1
        description: Flavor to run instance on for 1st VM type
    vm_0_image:
        type: string
        description: Image to run instance on for 1st VM type

resources:
    vm_0_group:
        type: "OS::Heat::ResourceGroup"
        properties:
            count: {get_param: vm_0_count}
            resource_def:
                type: generic-server.yaml
                properties:
                    job_name: {get_param: job_name}
                    ssh_key: {get_param: ssh_key}
                    index: "%index%"
                    group: "0"
                    vm_flavor: {get_param: vm_0_flavor}
                    vm_image: {get_param: vm_0_image}

outputs:
    vm_0_ips:
        description: IP addresses of the 1st vm types
        value: {get_attr: [vm_0_group, ip]}
