# This Ansible playbook adds packages to the
# O-RAN-SC build minion image that has Docker.
---
- import_playbook: ../common-packer/provision/docker.yaml

- hosts: all
  become_user: root
  become_method: sudo

  vars:
    golang_version: 1.12

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - include_role:
        name: geerlingguy.ruby
      vars:
        ruby_install_gems:
          - rake
        ruby_install_bundler: false
        ruby_install_from_source: true
        ansible_become: true

    - name: 'Install PackageCloud'
      command: 'gem install package_cloud'
      become: true

    - include_role:
        name: gantsign.golang
      vars:
        golang_version: {{ golang_version }}
        ansible_become: true

    - name: Add Go to Ubuntu path
      copy:
        dest: /etc/profile.d/custom-path.sh
        content: 'PATH=$PATH:/opt/go/{{ golang_version }}/bin'
      when: ansible_distribution == 'Ubuntu'
      become: yes
