#!/bin/bash
until host github.com &>/dev/null
do
    echo "Waiting until github.com is resolvable..."
done
git clone https://github.com/lfit/releng-global-jjb.git /opt/global-jjb
/opt/global-jjb/jenkins-init-scripts/init.sh