DOCKER_REGISTRY=nexus3.o-ran-sc.org
GERRIT_URL=https://gerrit.o-ran-sc.org/r
GIT_URL=ssh://oran-jobbuilder@gerrit.o-ran-sc.org:29418
JENKINS_HOSTNAME=vex-sjc-oran-jenkins-sandbox-1
LOGS_SERVER=https://logs.o-ran-sc.org
NEXUS_URL=https://nexus.o-ran-sc.org
REGISTRY_PORTS=10001 10002 10003 10004
S3_BUCKET=
SIGUL_BRIDGE_IP=54.71.144.162
SIGUL_KEY=oran-sandbox
SILO=sandbox
MASTER_RTD_PROJECT=doc-test
