DOCKER_REGISTRY=nexus3.o-ran-sc.org
GERRIT_URL=https://gerrit.o-ran-sc.org/r
GIT_URL=ssh://oran-jobbuilder@gerrit.o-ran-sc.org:29418
JENKINS_HOSTNAME=vex-sjc-oran-jenkins-prod-1
LOGS_SERVER=https://logs.o-ran-sc.org
NEXUS_URL=https://nexus.o-ran-sc.org
REGISTRY_PORTS=10001 10002 10003 10004
RELEASE_EMAIL=collab-it+o-ran-sc-release@linuxfoundation.org
RELEASE_USERNAME=o-ran-sc-release
S3_BUCKET=
SIGUL_BRIDGE_IP=44.232.126.158
SIGUL_KEY=oran-release-2019
SILO=production
MASTER_RTD_PROJECT=doc
