---
- parameter:
    name: kubernetes-stack-1-type
    parameters:
      - string:
          name: VM_0_COUNT
          default: '{vm_0_count}'
          description: 'Number of systems to spawn for vm 0'
      - string:
          name: VM_0_FLAVOR
          default: '{vm_0_flavor}'
          description: 'VM flavor to use for vm 0'
      - string:
          name: VM_0_IMAGE
          default: '{vm_0_image}'
          description: 'VM image to use for vm 0'

- builder:
    name: kubernetes-stack-1-type
    builders:
      - lf-stack-create:
          openstack-cloud: '{openstack-cloud}'
          openstack-heat-template: '{openstack-heat-template}'
          openstack-heat-template-dir: '{openstack-heat-template-dir}'
          openstack-heat-parameters: |
              vm_0_count: '$VM_0_COUNT'
              vm_0_flavor: '$VM_0_FLAVOR'
              vm_0_image: '$VM_0_IMAGE'
